id: A987ADCEA
title: 'Words to Delight the Lake-Born One: A Prayer for the Spread of the Vajrayāna
  Teachings of the Ancient Translations'
type: translation
pechas:
- I9947F12B
- I8AA9EC2E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:50.416047
  last_modified_at: 2023-01-04 12:07:50.416057
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I9947F12B/D86D: CAF3
  I8AA9EC2E/6DA5: CAF3
